"""
Render a PLY point cloud to a PNG image using Open3D (headless).

Produces a top-down view and a perspective view — useful for generating
figures for the report without needing a GUI point cloud viewer.

Usage
─────
    # From a PLY generated by quick_test or run_video:
    python scripts/render_ply.py reports/danger_map/quick_test/sample_cloud.ply

    # Custom output directory:
    python scripts/render_ply.py reports/danger_map/quick_test/sample_cloud.ply --out_dir figures/pointcloud

Outputs
    <out_dir>/pointcloud_topdown.png    — bird's-eye / top-down view
    <out_dir>/pointcloud_perspective.png — angled 3D perspective view

Dependencies
    pip install open3d   (headless rendering — no display needed)
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


def render_ply(ply_path: Path, out_dir: Path, width: int = 1280, height: int = 720) -> None:
    import open3d as o3d

    out_dir.mkdir(parents=True, exist_ok=True)
    pcd = o3d.io.read_point_cloud(str(ply_path))

    if pcd.is_empty():
        raise RuntimeError(f"PLY is empty or failed to load: {ply_path}")

    print(f"Loaded {len(pcd.points)} points from {ply_path}")

    # Camera coordinate frame: +X right, +Y down, +Z forward.
    # For a nice perspective view, look slightly downward from behind and above.
    # For top-down view, look straight down along -Y.

    vis = o3d.visualization.Visualizer()
    vis.create_window(width=width, height=height, visible=False)
    vis.add_geometry(pcd)

    opt = vis.get_render_option()
    opt.background_color = np.array([0.1, 0.1, 0.12])
    opt.point_size = 2.0

    # ── Perspective view ─────────────────────────────────────────────────────
    ctr = vis.get_view_control()
    ctr.set_front([0.0, -0.4, -0.9])
    ctr.set_lookat(np.mean(np.asarray(pcd.points), axis=0))
    ctr.set_up([0.0, -1.0, 0.0])
    ctr.set_zoom(0.5)

    vis.poll_events()
    vis.update_renderer()
    persp_path = out_dir / "pointcloud_perspective.png"
    vis.capture_screen_image(str(persp_path), do_render=True)
    print(f"  Perspective → {persp_path}")

    # ── Top-down view ────────────────────────────────────────────────────────
    ctr.set_front([0.0, -1.0, 0.0])
    ctr.set_up([0.0, 0.0, -1.0])
    ctr.set_zoom(0.6)

    vis.poll_events()
    vis.update_renderer()
    topdown_path = out_dir / "pointcloud_topdown.png"
    vis.capture_screen_image(str(topdown_path), do_render=True)
    print(f"  Top-down    → {topdown_path}")

    vis.destroy_window()


def render_ply_matplotlib(ply_path: Path, out_dir: Path) -> None:
    """Fallback renderer using matplotlib when Open3D is not available."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

    out_dir.mkdir(parents=True, exist_ok=True)

    # Parse PLY manually (ASCII format written by navigate.py)
    pts, colors = [], []
    in_body = False
    n_verts = 0
    with open(ply_path) as f:
        for line in f:
            if line.startswith("element vertex"):
                n_verts = int(line.split()[-1])
            elif line.strip() == "end_header":
                in_body = True
                continue
            elif in_body:
                parts = line.split()
                pts.append([float(parts[0]), float(parts[1]), float(parts[2])])
                colors.append([int(parts[3]) / 255.0,
                               int(parts[4]) / 255.0,
                               int(parts[5]) / 255.0])
    pts = np.array(pts)
    colors = np.array(colors)
    print(f"Loaded {len(pts)} points from {ply_path}")

    # Subsample for rendering speed
    max_pts = 50000
    if len(pts) > max_pts:
        idx = np.random.default_rng(42).choice(len(pts), max_pts, replace=False)
        pts, colors = pts[idx], colors[idx]

    # ── Perspective view ─────────────────────────────────────────────────────
    fig = plt.figure(figsize=(12, 8), facecolor="#1a1a1e")
    ax = fig.add_subplot(111, projection="3d", facecolor="#1a1a1e")
    ax.scatter(pts[:, 0], pts[:, 2], -pts[:, 1],
               c=colors, s=0.3, alpha=0.8, edgecolors="none")
    ax.set_xlabel("X (right)", color="white", fontsize=9)
    ax.set_ylabel("Z (forward)", color="white", fontsize=9)
    ax.set_zlabel("Y (up)", color="white", fontsize=9)
    ax.tick_params(colors="gray", labelsize=7)
    ax.view_init(elev=25, azim=-60)
    ax.set_title("Risk Point Cloud — Perspective", color="white", fontsize=12, pad=10)
    persp_path = out_dir / "pointcloud_perspective.png"
    fig.savefig(persp_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Perspective → {persp_path}")

    # ── Top-down view ────────────────────────────────────────────────────────
    fig = plt.figure(figsize=(12, 8), facecolor="#1a1a1e")
    ax = fig.add_subplot(111, facecolor="#1a1a1e")
    ax.scatter(pts[:, 0], pts[:, 2], c=colors, s=0.3, alpha=0.8, edgecolors="none")
    ax.set_xlabel("X (right)", color="white", fontsize=9)
    ax.set_ylabel("Z (forward)", color="white", fontsize=9)
    ax.tick_params(colors="gray", labelsize=7)
    ax.set_title("Risk Point Cloud — Top-Down", color="white", fontsize=12, pad=10)
    ax.set_aspect("equal")
    topdown_path = out_dir / "pointcloud_topdown.png"
    fig.savefig(topdown_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Top-down    → {topdown_path}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Render a PLY risk point cloud to PNG images.")
    ap.add_argument("ply_path", help="Path to the .ply file produced by navigate.py")
    ap.add_argument("--out_dir", default="figures/pointcloud",
                    help="Output directory for rendered PNGs. Default: figures/pointcloud")
    ap.add_argument("--width", type=int, default=1280)
    ap.add_argument("--height", type=int, default=720)
    args = ap.parse_args()

    ply_path = Path(args.ply_path)
    out_dir = Path(args.out_dir)

    try:
        import open3d  # noqa: F401
        render_ply(ply_path, out_dir, args.width, args.height)
    except ImportError:
        print("Open3D not available — falling back to matplotlib renderer.")
        render_ply_matplotlib(ply_path, out_dir)

    print("Done.")


if __name__ == "__main__":
    main()
